#!/bin/sh

case "$1" in
start)
    java -jar EssenceRuntime.jar &
    echo $! > /var/run/essenceruntime.pid
    ;;

stop)
    if [ ! -f /var/run/essenceruntime.pid ]; then
        echo "EssenceRuntime: not running"
        exit 1
    fi

    kill -TERM `cat /var/run/essenceruntime.pid`
    ;;

reload)
    if [ ! -f /var/run/my-java-program.pid ]; then
        echo "EssenceRuntime: not running"
        exit 1
    fi

    kill -TERM `cat /var/run/essenceruntime.pid`
    java -jar EssenceRuntime.jar &
    ;;

*)
    echo "Usage: /etc/init.d/essenceruntime {start|stop|reload}"
    exit 1
    ;;

esac

exit 0
