/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Francesco' at '4/10/17 2:29 PM' with Gradle 3.1
 *
 * @author Francesco, @date 4/10/17 2:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
